
version: '3'

services:

  monoapp-service-container:
    container_name: monoapp-service-container
    build:
      context: ../
      dockerfile: build-config/Dockerfile
    #volumes:
      #- ${USERPROFILE}/docker-volumes/.keycloak/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ${USERPROFILE}/docker-volumes/.keycloak/nginx-certs/server:/etc/nginx/certs/
      #- ${USERPROFILE}/docker-volumes/.keycloak/nginx-certs/trusted:/usr/local/share/ca-certificates:ro
    ports:
      - 8089:80
      #- 443:443 
    restart: always
    #depends_on:
      #- keycloak-container
    networks:
      - monoapp_service_network

networks:
  monoapp_service_network:
    name: monoapp_service_network
    driver: bridge