name: publish docker image in Github Packages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  publish-docker-image:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: . # The build context (usually the root of your repo)
          file: ./build-config/Dockerfile # Path to your Dockerfile (relative to the context)
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/monolithic-app-service:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}